SELECT * FROM CUSTOMER; --- * means all columns

SELECT CUSTOMER_ID, NAME FROM CUSTOMER; --- SELECT specific columns

SELECT * FROM PRODUCT;

SELECT
	PRODUCT_ID,
	DESCRIPTION,
	PRICE,
	PRICE * 1.07 AS TAXED_PRICE --- SELECT with expression. This column is not in the table
FROM PRODUCT;

SELECT
	PRODUCT_ID,
	DESCRIPTION,
	PRICE AS UNTAXED_PRICE,
	PRICE * 1.07 AS TAXED_PRICE
FROM PRODUCT;

SELECT
	PRODUCT_ID,
	DESCRIPTION,
	PRICE,
	ROUND(
		PRICE * 1.07,
		2
	) AS TAXED_PRICE
FROM PRODUCT;

SELECT
	NAME,
	CITY || ', ' || STATE AS LOCATION --- CONCATENATION
FROM CUSTOMER;


SELECT
	NAME,
	STREET_ADDRESS || ' ' || CITY || ', ' || STATE || ' ' || ZIP AS SHIP_ADDRESS
FROM CUSTOMER;

--- MANY DATABASES USES PIPE AS CONCAT, HOWEVER SOME OF THEM USE CONCAT() FUNCTION INSTEAD
	